2023-05-04T16:32:08.954671493Z W0504 16:32:08.954607       1 main.go:227] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
2023-05-04T16:32:08.954671493Z I0504 16:32:08.954626       1 main.go:346] cookies are secure!
2023-05-04T16:32:08.972278229Z E0504 16:32:08.972152       1 auth.go:232] error contacting auth provider (retrying in 10s): Get "https://kubernetes.default.svc/.well-known/oauth-authorization-server": dial tcp: lookup kubernetes.default.svc on 172.30.0.10:53: read udp 10.128.0.93:45745->172.30.0.10:53: read: connection refused
2023-05-04T16:32:18.979192840Z E0504 16:32:18.979122       1 auth.go:232] error contacting auth provider (retrying in 10s): Get "https://kubernetes.default.svc/.well-known/oauth-authorization-server": dial tcp: lookup kubernetes.default.svc on 172.30.0.10:53: read udp 10.128.0.93:50481->172.30.0.10:53: read: connection refused
2023-05-04T16:32:28.983730010Z E0504 16:32:28.983689       1 auth.go:232] error contacting auth provider (retrying in 10s): Get "https://kubernetes.default.svc/.well-known/oauth-authorization-server": dial tcp: lookup kubernetes.default.svc on 172.30.0.10:53: read udp 10.128.0.93:41812->172.30.0.10:53: read: connection refused
2023-05-04T16:32:38.988479178Z E0504 16:32:38.988436       1 auth.go:232] error contacting auth provider (retrying in 10s): Get "https://kubernetes.default.svc/.well-known/oauth-authorization-server": dial tcp: lookup kubernetes.default.svc on 172.30.0.10:53: read udp 10.128.0.93:47842->172.30.0.10:53: read: connection refused
2023-05-04T16:32:49.047022089Z E0504 16:32:49.046980       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:32:59.073260067Z E0504 16:32:59.073219       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:09.093006436Z E0504 16:33:09.092369       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:19.138209222Z E0504 16:33:19.135333       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:29.167123579Z E0504 16:33:29.158599       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:39.165150229Z E0504 16:33:39.165101       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:49.171756180Z E0504 16:33:49.171717       1 auth.go:232] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.sno.gw.lo/oauth/token failed: Head "https://oauth-openshift.apps.sno.gw.lo": dial tcp 192.168.1.126:443: connect: connection refused
2023-05-04T16:33:59.337801030Z I0504 16:33:59.337767       1 main.go:796] Binding to [::]:8443...
2023-05-04T16:33:59.337801030Z I0504 16:33:59.337793       1 main.go:798] using TLS
2023-05-04T18:30:52.191008051Z 2023/05/04 18:30:52 Failed to dial backend: 'websocket: bad handshake' Status: '400 Bad Request' URL: 'https://kubernetes.default.svc/api/v1/namespaces/openshift-apiserver/pods/apiserver-65d8786fff-b42ll/log?cluster=local-cluster&container=openshift-apiserver&follow=true&previous=true'
2023-05-04T18:33:23.442099864Z 2023/05/04 18:33:23 Failed to dial backend: 'websocket: bad handshake' Status: '400 Bad Request' URL: 'https://kubernetes.default.svc/api/v1/namespaces/openshift-etcd/pods/etcd-node/log?cluster=local-cluster&container=etcdctl&follow=true&previous=true'
2023-05-04T18:33:25.771763524Z 2023/05/04 18:33:25 Failed to dial backend: 'websocket: bad handshake' Status: '400 Bad Request' URL: 'https://kubernetes.default.svc/api/v1/namespaces/openshift-etcd/pods/etcd-node/log?cluster=local-cluster&container=etcdctl&follow=true&previous=true'
2023-05-04T18:33:26.312013411Z 2023/05/04 18:33:26 Failed to dial backend: 'websocket: bad handshake' Status: '400 Bad Request' URL: 'https://kubernetes.default.svc/api/v1/namespaces/openshift-etcd/pods/etcd-node/log?cluster=local-cluster&container=etcdctl&follow=true&previous=true'
